# Generated by Django 5.1.3 on 2025-02-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='A', max_length=1)),
                ('period1', models.BooleanField(default=False)),
                ('period2', models.BooleanField(default=False)),
                ('period3', models.BooleanField(default=False)),
                ('period4', models.BooleanField(default=False)),
                ('period5', models.BooleanField(default=False)),
                ('period6', models.BooleanField(default=False)),
                ('period7', models.BooleanField(default=False)),
                ('period8', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_records.student')),
            ],
        ),
    ]
