# Generated by Django 5.1.3 on 2025-02-26 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0004_remove_attendance_student_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_records.attendance'),
        ),
    ]
