# Generated by Django 5.1.3 on 2025-02-26 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_records', '0005_alter_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
